### ISSUE TITLE
Subkernels

### ISSUE THREAD

**Issue by minad** [blink1073/metakernel#41]
In my original proposal I thought about using the metakernel to redirect to a subkernel via 0mq depending on the current cell language or magic. This allows us to use IJulia, IRuby, IHaskell and all these other nice kernels enhanced with magics and working together in a single notebook. What do you think?

The difference is that the subkernels don't have to be in python compared to what we have now here.

**Comment by dsblank** [comment]
I think we can close this for now. If someone develops an implementation to replace the current MetaKernel for version Metakernel 2.0, that will be fine (although it should allow current kernels based on Metakernel to keep workings, perhaps with changes).
