### ISSUE TITLE
Shift+Tab Help doesn't respect cursor position

### ISSUE THREAD

**Issue by dsblank** [blink1073/metakernel#58]
If you use `Shift + Tab` in the notebook, it always gives help on the last item.

Example, enter the first in a cell, and begin typing the second:

```python
In [1]: import math
In [ ]: x = math.sin(math.cos
```
If you put the cursor at end and press `Shift + Tab` then help on `cos` appears. If you move the cursor to right after sin and press `Shift + Tab` then you should get help on `sin`, but help appears on `cos`.

I suspect that full_obj is wrong. None of the fields in `info` are just `sin`.

**Comment by blink1073** [comment]
When I use `Shift + Tab` it takes me to the previous cell, any idea why?

**Comment by blink1073** [comment]
N/m, I needed to nuke my `~/.ipython` folder.

**Comment by blink1073** [comment]
Ha, my commit closed the issue.  Feel free to reopen if it does not work for you, but it Worked On My Machine (TM).
